// <auto-generated />
using System;
using LisanBits.DataPipeline.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LisanBits.DataPipeline.Migrations
{
    [DbContext(typeof(PipelineDbContext))]
    [Migration("20260608133638_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("LisanBits.DataPipeline.Data.Models.CrawledUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId", "Url")
                        .IsUnique();

                    b.ToTable("CrawledUrlQueue");
                });

            modelBuilder.Entity("LisanBits.DataPipeline.Data.Models.DataSourceConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscoveryXPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkXPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaginationParam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetXPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataSourceConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUrl = "https://shamela.ws/book/1687",
                            Category = "Linguistics",
                            IsActive = true,
                            Name = "Shamela (Lexicon)",
                            PaginationParam = "/",
                            TargetXPath = "//div[contains(@class, 'nass')]"
                        },
                        new
                        {
                            Id = 2,
                            BaseUrl = "https://sunnah.com/",
                            Category = "Religion",
                            DiscoveryXPath = "//a[starts-with(@href, '/') and string-length(@href) > 1 and not(contains(@href, '#')) and not(contains(@href, 'about')) and not(contains(@href, 'contact')) and not(contains(@href, 'help'))]",
                            IsActive = true,
                            Name = "Sunnah.com (All Books)",
                            PaginationParam = "",
                            TargetXPath = "//div[contains(@class, 'arabic_hadith_full')]"
                        },
                        new
                        {
                            Id = 8,
                            BaseUrl = "file:///d:/A_S/LisanBitModel/quran-uthmani.xml",
                            Category = "Religion",
                            IsActive = true,
                            Name = "Tanzil Quran",
                            PaginationParam = "",
                            TargetXPath = "//aya"
                        },
                        new
                        {
                            Id = 9,
                            BaseUrl = "https://ar.wikipedia.org/wiki/تصنيف:علم",
                            Category = "Science",
                            DiscoveryXPath = "//div[@id='mw-subcategories']//a | //div[@id='mw-pages']//a",
                            IsActive = true,
                            LinkXPath = "//div[@id='mw-pages']//a",
                            Name = "Wikipedia (Science)",
                            PaginationParam = "",
                            TargetXPath = "//div[@id='mw-content-text']//p"
                        },
                        new
                        {
                            Id = 10,
                            BaseUrl = "https://academy.hsoub.com/",
                            Category = "Science",
                            DiscoveryXPath = "//h4[contains(@class, 'ipsDataItem_title')]//a | //a[contains(@href, 'page/')]",
                            IsActive = true,
                            LinkXPath = "//h4[contains(@class, 'ipsDataItem_title')]//a",
                            Name = "Hsoub Academy (All)",
                            PaginationParam = "",
                            TargetXPath = "//div[contains(@class, 'ipsType_normal')]"
                        },
                        new
                        {
                            Id = 15,
                            BaseUrl = "https://altibbi.com/مصطلحات-طبية",
                            Category = "Medical",
                            DiscoveryXPath = "//a[contains(@href, '/مصطلحات-طبية/')]",
                            IsActive = true,
                            LinkXPath = "//a[contains(@href, '/مصطلحات-طبية/')]",
                            Name = "Altibbi (Medical)",
                            PaginationParam = "?page=",
                            TargetXPath = "//div[contains(@class, 'definition-content')]"
                        },
                        new
                        {
                            Id = 16,
                            BaseUrl = "https://ar.wikipedia.org/wiki/تصنيف:طب",
                            Category = "Medical",
                            DiscoveryXPath = "//div[@id='mw-subcategories']//a | //div[@id='mw-pages']//a",
                            IsActive = true,
                            LinkXPath = "//div[@id='mw-pages']//a",
                            Name = "Wikipedia (Medicine)",
                            PaginationParam = "",
                            TargetXPath = "//div[@id='mw-content-text']//p"
                        },
                        new
                        {
                            Id = 17,
                            BaseUrl = "https://sa.investing.com/education/terms",
                            Category = "Finance",
                            DiscoveryXPath = "//div[contains(@class, 'textDiv')]//a | //div[contains(@class, 'midDiv')]//a | //div[contains(@class, 'sideDiv')]//a",
                            IsActive = true,
                            LinkXPath = "//div[contains(@class, 'textDiv')]//a | //div[contains(@class, 'midDiv')]//a | //div[contains(@class, 'sideDiv')]//a",
                            Name = "Investing.com",
                            PaginationParam = "?page=",
                            TargetXPath = "//div[contains(@class, 'WYSIWYG')]"
                        },
                        new
                        {
                            Id = 18,
                            BaseUrl = "https://www.aleqt.com/",
                            Category = "Finance",
                            DiscoveryXPath = "//h3//a | //h2//a | //div[contains(@class, 'flex-col')]//a",
                            IsActive = true,
                            LinkXPath = "//h3//a | //h2//a | //div[contains(@class, 'flex-col')]//a",
                            Name = "Al-Eqtisad",
                            PaginationParam = "?page=",
                            TargetXPath = "//div[contains(@class, 'article-content')]/div[not(@class) or @class='']"
                        },
                        new
                        {
                            Id = 19,
                            BaseUrl = "https://www.hindawi.org/books/categories/novels/",
                            Category = "Literature",
                            DiscoveryXPath = "//div[contains(@class, 'book-list')]//a",
                            IsActive = false,
                            LinkXPath = "//div[contains(@class, 'book-list')]//a",
                            Name = "Hindawi (Novels)",
                            PaginationParam = "",
                            TargetXPath = "//div[@id='book-content']"
                        },
                        new
                        {
                            Id = 20,
                            BaseUrl = "https://raw.githubusercontent.com/Mostafanofal453/2.5-Million-Rows-Egyptian-Datasets-Collection/main/dataset.csv",
                            Category = "Slang",
                            IsActive = false,
                            Name = "Egyptian Slang (Nofal)",
                            PaginationParam = "",
                            TargetXPath = "CSV"
                        },
                        new
                        {
                            Id = 21,
                            BaseUrl = "https://www.kooora.com/",
                            Category = "Sports",
                            DiscoveryXPath = "//td[contains(@class, 'news_title')]//a | //a[contains(@href, '?n=')] | //a[contains(@href, '%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1') or contains(@href, '/أخبار/')]",
                            IsActive = true,
                            LinkXPath = "//td[contains(@class, 'news_title')]//a | //a[contains(@href, '?n=')] | //a[contains(@href, '%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1') or contains(@href, '/أخبار/')]",
                            Name = "Kooora",
                            PaginationParam = "",
                            TargetXPath = "//div[contains(@id, 'article_body')]"
                        },
                        new
                        {
                            Id = 22,
                            BaseUrl = "https://www.aljazeera.net/",
                            Category = "News",
                            DiscoveryXPath = "//a[starts-with(@href, '/') and (contains(@href, '/news/') or contains(@href, '/sport/'))] | //a[contains(@href, 'aljazeera.net/news/') or contains(@href, 'aljazeera.net/sport/')]",
                            IsActive = false,
                            LinkXPath = "//a[starts-with(@href, '/') and (contains(@href, '/news/') or contains(@href, '/sport/'))] | //a[contains(@href, 'aljazeera.net/news/') or contains(@href, 'aljazeera.net/sport/')]",
                            Name = "Al Jazeera",
                            PaginationParam = "",
                            TargetXPath = "//div[contains(@class, 'wysiwyg')]"
                        },
                        new
                        {
                            Id = 23,
                            BaseUrl = "https://www.skynewsarabia.com/",
                            Category = "News",
                            DiscoveryXPath = "//a[contains(@class, 'article-title') or contains(@href, '/world/') or contains(@href, '/middle-east/') or contains(@href, '/live-story/')]",
                            IsActive = false,
                            LinkXPath = "//a[contains(@class, 'article-title') or contains(@href, '/world/') or contains(@href, '/middle-east/') or contains(@href, '/live-story/')]",
                            Name = "Sky News Arabia",
                            PaginationParam = "",
                            TargetXPath = "//div[contains(@class, 'article-body')]"
                        },
                        new
                        {
                            Id = 24,
                            BaseUrl = "https://ar.wikihow.com/الصفحة-الرئيسية",
                            Category = "DailyLife",
                            DiscoveryXPath = "//a[contains(@class, 'related-article')]",
                            IsActive = false,
                            LinkXPath = "//a[contains(@class, 'related-article')]",
                            Name = "WikiHow Arabic",
                            PaginationParam = "",
                            TargetXPath = "//div[contains(@class, 'step')]"
                        },
                        new
                        {
                            Id = 25,
                            BaseUrl = "https://www.youm7.com/",
                            Category = "News",
                            DiscoveryXPath = "//h3//a | //h2//a | //a[contains(@href, '/story/') or contains(@href, '/news/')]",
                            IsActive = true,
                            LinkXPath = "//h3//a | //h2//a | //a[contains(@href, '/story/') or contains(@href, '/news/')]",
                            Name = "Youm7 (News)",
                            PaginationParam = "",
                            TargetXPath = "//div[contains(@class, 'article-text')]//p | //div[@id='articleBody']//p"
                        },
                        new
                        {
                            Id = 26,
                            BaseUrl = "https://www.masrawy.com/news",
                            Category = "News",
                            DiscoveryXPath = "//a[contains(@href, '/news/') or contains(@href, '/article/')]",
                            IsActive = true,
                            LinkXPath = "//a[contains(@href, '/news/') or contains(@href, '/article/')]",
                            Name = "Masrawy (News)",
                            PaginationParam = "",
                            TargetXPath = "//div[contains(@class, 'article-body')]//p | //div[contains(@class, 'news-body')]//p"
                        },
                        new
                        {
                            Id = 27,
                            BaseUrl = "https://ar.wikipedia.org/wiki/تصنيف:أدب",
                            Category = "Literature",
                            DiscoveryXPath = "//div[@id='mw-subcategories']//a | //div[@id='mw-pages']//a",
                            IsActive = true,
                            LinkXPath = "//div[@id='mw-pages']//a",
                            Name = "Wikipedia (Literature)",
                            PaginationParam = "",
                            TargetXPath = "//div[@id='mw-content-text']//p"
                        },
                        new
                        {
                            Id = 28,
                            BaseUrl = "https://ar.wikipedia.org/wiki/تصنيف:حياة_يومية",
                            Category = "DailyLife",
                            DiscoveryXPath = "//div[@id='mw-subcategories']//a | //div[@id='mw-pages']//a",
                            IsActive = true,
                            LinkXPath = "//div[@id='mw-pages']//a",
                            Name = "Wikipedia (DailyLife)",
                            PaginationParam = "",
                            TargetXPath = "//div[@id='mw-content-text']//p"
                        },
                        new
                        {
                            Id = 29,
                            BaseUrl = "file:///D:/A_S/nofal_slang.csv",
                            Category = "Slang",
                            IsActive = false,
                            Name = "Nofal Slang (Local CSV)",
                            PaginationParam = "",
                            TargetXPath = "CSV_FILE"
                        },
                        new
                        {
                            Id = 30,
                            BaseUrl = "file:///D:/A_S/arb-egy-cmp-corpus_corrected.json",
                            Category = "Slang",
                            IsActive = false,
                            Name = "ARB-EGY-CMP (Local JSON)",
                            PaginationParam = "",
                            TargetXPath = "JSONL_TEXT_FILE"
                        },
                        new
                        {
                            Id = 31,
                            BaseUrl = "https://shamela.ws/book/7283",
                            Category = "Linguistics",
                            IsActive = true,
                            Name = "Shamela (Lexicon)_Moheet",
                            PaginationParam = "/",
                            TargetXPath = "//div[contains(@class, 'nass')]"
                        },
                        new
                        {
                            Id = 32,
                            BaseUrl = "https://shamela.ws/book/7030",
                            Category = "Linguistics",
                            IsActive = true,
                            Name = "Shamela (Lexicon)_Tag_Aroos",
                            PaginationParam = "/",
                            TargetXPath = "//div[contains(@class, 'nass')]"
                        },
                        new
                        {
                            Id = 33,
                            BaseUrl = "https://shamela.ws/book/7028",
                            Category = "Linguistics",
                            IsActive = true,
                            Name = "Shamela (Lexicon)_Wasset",
                            PaginationParam = "/",
                            TargetXPath = "//div[contains(@class, 'nass')]"
                        },
                        new
                        {
                            Id = 34,
                            BaseUrl = "https://shamela.ws/book/1682",
                            Category = "Linguistics",
                            IsActive = true,
                            Name = "Shamela (Lexicon)_AlAin",
                            PaginationParam = "/",
                            TargetXPath = "//div[contains(@class, 'nass')]"
                        },
                        new
                        {
                            Id = 35,
                            BaseUrl = "https://shamela.ws/book/150964",
                            Category = "Linguistics",
                            IsActive = true,
                            Name = "Shamela (Lexicon)_Taimoor",
                            PaginationParam = "/",
                            TargetXPath = "//div[contains(@class, 'nass')]"
                        });
                });

            modelBuilder.Entity("LisanBits.DataPipeline.Data.Models.LexiconEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Antonyms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plurals")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Root")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceBook")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Synonyms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Root");

                    b.HasIndex("Word");

                    b.ToTable("LexiconEntries");
                });

            modelBuilder.Entity("LisanBits.DataPipeline.Data.Models.ProcessedUniversalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContextVector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PosSequence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RawDataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootSequence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProcessedUniversalData");
                });

            modelBuilder.Entity("LisanBits.DataPipeline.Data.Models.RawUniversalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SentenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WordCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RawUniversalData");
                });

            modelBuilder.Entity("LisanBits.DataPipeline.Data.Models.ScrapeJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastProcessedIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceName", "TargetId")
                        .IsUnique();

                    b.ToTable("ScrapeJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
